---
- name: Restart cron
  ansible.builtin.service:
    name: "{{ cron_service_fact_key | default(cron_service) }}"
    state: restarted
  when:
    - ansible_facts['service_mgr'] == 'systemd'
    - (cron_service_fact_key | default(cron_service) | default('')) | length > 0
  tags:
    - cron
    - service
